---
abstract: 'Add a file() method to Git::Repository'
author:
  - 'Nathaniel G. Nutter <nnutter@cpan.org>'
build_requires:
  Class::Inspector: 0
  Git::Repository::Plugin::Test: 0.002
  Test::Fatal: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.008, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Git-Repository-Plugin-File
requires:
  Carp: 0
  Git::Repository: 1.13
  Path::Class: 0
resources:
  repository: git://github.com/nnutter/Git-Repository-Plugin-File.git
version: 0.005
